---
version: 2
updates:
  - package-ecosystem: docker
    schedule:
      interval: weekly
      time: '02:00'
  - package-ecosystem: pip
    directory: /ci
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 99
