---
name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    name: Rebuild
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - '7.0'
          - '7.2'
          - '7.4'
          - '7.6'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - run: make pull
      - run: make build
      - run: make acceptance

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-mapserver'

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
